/* Generated by tools/import_audio.py */
#define AUDIO_HIT 0
#define AUDIO_HIT2 1
#define AUDIO_HIT3 2
#define AUDIO_GOAL 3
#define AUDIO_JUMP 4
#define AUDIO_MOVE 5
#define AUDIO_SELECT 6
#define AUDIO_BOOST 7
#define AUDIO_MUSIC 8
#define AUDIO_COUNT 9
