"""Bake a lit sphere into ROM: 64 rolling frames, no runtime lighting or triangles."""
from pathlib import Path
import math
size = 64
phi = (1 + math.sqrt(5)) / 2
centers = [(0,a,b*phi) for a in (-1,1) for b in (-1,1)]
centers += [(a,b*phi,0) for a in (-1,1) for b in (-1,1)]
centers += [(b*phi,0,a) for a in (-1,1) for b in (-1,1)]
centers = [tuple(v/math.sqrt(1+phi*phi) for v in c) for c in centers]
frames=[]
for frame in range(64):
    angle=frame*math.tau/64
    c,s=math.cos(angle),math.sin(angle)
    pixels=[]
    for y in range(size):
        for x in range(size):
            nx,ny=(x+0.5-size/2)/(size/2),(size/2-y-0.5)/(size/2)
            r2=nx*nx+ny*ny
            if r2>=1:
                pixels.append(0)
                continue
            nz=math.sqrt(1-r2)
            # Fixed upper-left lighting; only the surface panels rotate.
            light=max(0,-0.35*nx+0.45*ny+0.82*nz)
            shade=12+round(19*light)
            u,v,w=c*nx+s*nz,ny,-s*nx+c*nz
            dots=sorted((u*a+v*b+w*d for a,b,d in centers),reverse=True)
            if dots[0]-dots[1]<0.035:
                shade=max(7,shade-7)
            pixels.append(192+min(31,shade))
    frames.append(pixels)
out=['/* Generated by tools/gen_ball_sprite.py; const data stays in ROM. */',
     'static const u8 ball_sprite[64][64*64] = {']
for pixels in frames:
    out.append('{')
    out.extend(','.join(map(str,pixels[i:i+64]))+',' for i in range(0,len(pixels),64))
    out.append('},')
out.append('};')
Path(__file__).resolve().parents[1].joinpath('ball_sprite.inc').write_text('\n'.join(out)+'\n')
