"""Build small closed, outward-wound car components with atlas UVs. No assets required."""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]

def build(kind, detail=0):
    vertices, faces = [], []
    def tri(ids, tile, uv=None, material=3):
        x,y=(tile%4)*16,(tile//4)*32
        uv=uv or [(0,31),(15,31),(15,0)]
        faces.append((ids, material, [(x+u,y+v) for u,v in uv]))
    def solid(points, tiles, material=3):
        off=len(vertices); vertices.extend(points)
        for ids,tile in zip([(0,3,2,1),(0,1,5,4),(2,3,7,6),(0,4,7,3),(1,2,6,5),(4,5,6,7)],tiles):
            a,b,c,d=[off+i for i in ids]
            tri((a,b,c),tile,material=material)
            tri((a,c,d),tile,[(0,31),(15,0),(0,0)],material)
    def box(x0,x1,y0,y1,z0,z1,tiles,mat=3):
        solid([(x0,y0,z1),(x1,y0,z1),(x1,y0,z0),(x0,y0,z0),
               (x0,y1,z1),(x1,y1,z1),(x1,y1,z0),(x0,y1,z0)],tiles,mat)
    # Raised wedge nose, compact cabin, wide exposed wheels, elevated rear wing.
    width,length,height,roof=(10,18,8,17) if kind==0 else ((11,21,6,12) if kind==1 else (12,17,10,20))
    nose = length + (2 if detail == 2 else 0)
    solid([(-width,3,nose),(width,3,nose),(width,3,-length),(-width,3,-length),
           (-width+2,height-2,nose),(width-2,height-2,nose),(width,height,-length),(-width,height,-length)], [6,2,3,1,1,0])
    front,rear=(6,-11) if kind==0 else ((3,-12) if kind==1 else (10,-12))
    solid([(-width+1,height,front),(width-1,height,front),(width-1,height,rear),(-width+1,height,rear),
           (-7,roof,front-5),(7,roof,front-5),(7,roof,rear+2),(-7,roof,rear+2)], [6,4,4,4,4,0])
    # Garage: eight-sided wheels; match: six; distant silhouettes: four.
    segments = (8, 6, 4)[detail]
    for side in (-1,1):
        for z in (-11,11):
            off=len(vertices)
            for x in (side*10,side*15):
                for i in range(segments):
                    t=i*2*math.pi/segments
                    vertices.append((x,5+round(5*math.cos(t)),z+round(5*math.sin(t))))
            for i in range(segments):
                j=(i+1)%segments
                ids=[off+i,off+j,off+segments+j,off+segments+i]
                if side<0: ids.reverse()
                a,b,c,d=ids
                tri((a,b,c),6,material=132); tri((a,c,d),6,[(0,31),(15,0),(0,0)],132)
            for ring in (0,segments):
                for i in range(1,segments-1):
                    ids=[off+ring,off+ring+i,off+ring+i+1]
                    if (side>0)==(ring==0): ids.reverse()
                    uv=[(round(7.5+7.5*math.sin((v-off-ring)*2*math.pi/segments)),round(15.5-15.5*math.cos((v-off-ring)*2*math.pi/segments))) for v in ids]
                    tri(ids,5,uv,132)
    if detail < 2:
        box(-11,11,3,5,length,length+2,[6,2,6,6,6,6],132)
    if kind!=2:
        for x in (() if detail else (-7,6)): box(x,x+1,height,roof-1,-17,-15,[6]*6,132)
        box(-13,13,roof-1,roof+1,-20,-14,[6,7,3,7,7,0])
    else:
        box(-8,8,roof,roof+2,-10,3,[6,7,7,7,7,6],132)
    assert len(vertices)<=256 and len(faces)<=320
    return vertices,faces

def generate():
    out=['/* Generated by tools/generate_cars.py. Edit the generator, then regenerate. */']
    names=[('car','OCTANE'),('opp_car','STRIKER'),('rover','ROVER')]
    for detail,suffix in enumerate(('', '_match', '_far')):
        for k,(base,name) in enumerate(names):
            symbol=base+suffix
            vs,fs=build(k,detail)
            out.append(f'static const Vector3 {symbol}_vertices[] = {{')
            out += ['    { '+', '.join(str(c*256) for c in v)+' },' for v in vs]
            out.append('};\nstatic const Face '+symbol+'_faces[] = {')
            for ids,mat,uv in fs:
                out.append('    { '+', '.join(map(str,[*ids,mat]))+', { '+', '.join('{ %d, %d }'%p for p in uv)+' } },')
            out.append('};')
            out.append(f'static Vector3 {symbol}_normals[{len(fs)}] EWRAM_MODEL_DATA;')
            out.append(f'Mesh {symbol}_mesh = {{ "{name}", {len(vs)}, {len(fs)}, {symbol}_vertices, {symbol}_faces, {symbol}_normals }};')
        array=('car_models','car_match_models','car_far_models')[detail]
        out.append(f'const Mesh *const {array}[CAR_MODEL_COUNT] = {{ &car{suffix}_mesh, &opp_car{suffix}_mesh, &rover{suffix}_mesh }};')
    (ROOT/'car_models.inc').write_text('\n'.join(out)+'\n')
if __name__=='__main__': generate()
