"""Import the user's prepared WAV pack as aligned 8192-Hz signed PCM for GBA DMA."""
from pathlib import Path
import wave,struct,math,json,sys
root=Path(__file__).resolve().parents[1]
source=Path(sys.argv[1]) if len(sys.argv)>1 else root.parent/'RocketLeague-Audio/gba_audio/pcm'
# ID, source, maximum duration, gain. Two hardware channels share headroom.
clips=[('HIT','ball_hit_01',1.2,.65),('HIT2','ball_hit_02',1.2,.65),('HIT3','ball_hit_03',1.2,.65),
('GOAL','goal_explosion',6,.8),('JUMP','car_move_01',1,.45),
('MOVE','ui_01',.10,.12),('SELECT','ui_02',.20,.18),('BOOST','boost_loop',1.5,.36),('MUSIC','music_map_09',33,.25)]
data=bytearray();entries=[];report=[]
for ident,name,duration,gain in clips:
 path=root/'assets/audio/source/goal_explosion.wav' if ident=='GOAL' else source/(name+'.wav')
 with wave.open(str(path)) as w:
  assert w.getsampwidth()==2 and w.getnchannels()==1
  rate=w.getframerate();raw=w.readframes(min(w.getnframes(),int(duration*rate)))
 samples=struct.unpack('<'+'h'*(len(raw)//2),raw)
 mean=sum(samples)/len(samples);peak=max(abs(s-mean) for s in samples) or 1
 count=int(len(samples)*8192/rate);pcm=[]
 for i in range(count):
  p=i*rate/8192;a=int(p);f=p-a
  v=(samples[a]*(1-f)+samples[min(a+1,len(samples)-1)]*f-mean)/peak
  fade=min(1,i/64,(count-1-i)/128)
  pcm.append(round(v*127*gain*fade)&255)
 offset=len(data);data.extend(pcm)
 # IRQ housekeeping runs at VBlank even if simulation/rendering stalls.
 data.extend(bytes(512+(-len(data)%4)))
 frames=math.ceil(count*16777216/(8192*280896))
 entries.append((ident,offset,count,frames))
 report.append(dict(id=ident,source=str(path),samples=count,frames=frames,gain=gain))
(root/'assets/audio/sounds.bin').write_bytes(data)
(root/'assets/audio/sounds.h').write_text('/* Generated by tools/import_audio.py */\n'+''.join(f'#define AUDIO_{n} {i}\n' for i,(n,*_) in enumerate(entries))+'#define AUDIO_COUNT '+str(len(entries))+'\n')
(root/'assets/audio/sounds.inc').write_text('/* offset, samples, VBlanks */\n'+''.join('{%d,%d,%d},\n'%(o,n,f) for _,o,n,f in entries))
(root/'assets/audio/manifest.json').write_text(json.dumps(report,indent=2)+'\n')
print(f'Imported {len(entries)} clips: {len(data):,} ROM bytes, no sample RAM buffer')
